version: '3.1'

services:

  db1:
    image: postgres:15
    container_name: blog-public-db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD_1}
      POSTGRES_USER: ${DB_USER_1}
      POSTGRES_DB: ${DB_NAME_1}
    ports: 
      - ${DB_PORT_1}:5432
    volumes:
      - ./docker-data/db1:/var/lib/postgresql/data

  db2:
    image: postgres:15
    container_name: blog-auth-db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD_2}
      POSTGRES_USER: ${DB_USER_2}
      POSTGRES_DB: ${DB_NAME_2}
    ports: 
      - ${DB_PORT_2}:5432
    volumes:
      - ./docker-data/db2:/var/lib/postgresql/data